version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: database_psl
    restart: always
    environment:
      POSTGRES_DB: bd-admin-psl
      POSTGRES_USER: admin-psl
      POSTGRES_PASSWORD: psl-Admin-2OZE
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin-psl
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTER_PORT: 80
    ports:
      - 8300:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgresql-data: